export const GET_SUBSCRIPTION = "GET_SUBSCRIPTION";
export const GET_ALL_SUBSCRIPTION = "GET_ALL_SUBSCRIPTION";
export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";
export const SUBSCRIPTION_ERROR = "SUBSCRIPTION_ERROR";
export const UPDATE_STATUS = "UPDATE_STATUS";
